[package]
name = "mitmproxy_wireguard"
description = "WireGuard interface for mitmproxy"
license = "MIT"
publish = false

version = "0.1.0-dev"
edition = "2021"
rust-version = "1.56.0"

authors = ["Fabio Valentini <decathorpe@gmail.com>", "Maximilian Hils <cargo@maximilianhils.com>"]
exclude = ["/rustfmt.toml"]

[lib]
name = "mitmproxy_wireguard"
crate-type = ["cdylib"]

[dependencies]
boringtun = { version = "0.4", default-features = false }
smoltcp = "0.8"
pyo3 = { version = "0.16.4", features = ["extension-module", "anyhow"] }
pyo3-asyncio = { version = "0.16", features = ["tokio-runtime"] }
tokio = { version = "1.17", features = ["macros", "net", "rt-multi-thread", "sync", "time"] }
anyhow = "1.0.56"
log = "0.4.16"
env_logger = "0.9"
base64 = "0.13"
pretty-hex = "0.3.0"
console-subscriber = "0.1.4"
