[package]
name = "mitmguard"
description = "WireGuard interface for mitmproxy"
license = "MIT"
publish = false

version = "0.1.0-dev"
edition = "2021"
rust-version = "1.56.0"

authors = ["Fabio Valentini <decathorpe@gmail.com>"]
exclude = ["/rustfmt.toml"]

[lib]
name = "mitmproxy_wireguard"
crate-type = ["cdylib"]

[dependencies]
anyhow = "1.0.56"
base64 = "0.13"
boringtun = { version = "0.4", default-features = false }
console-subscriber = "0.1.3"
env_logger = "0.9"
log = "0.4.14"
pretty-hex = "0.2.1"
pyo3 = { version = "0.16.3", features = ["extension-module"] }
pyo3-asyncio = { version = "0.16", features = ["tokio-runtime"] }
smoltcp = "0.8"
tokio = { version = "1.15", features = ["macros", "net", "rt-multi-thread", "sync", "time"] }

[profile.release]
codegen-units = 1
lto = true
opt-level = 3
